import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Head from "next/head";

const roboto = Roboto({ subsets: ["latin"], weight: '700' });

export const metadata = {
  title: "E-Commerce",
  description: "Generated by create next app",
  icon: "/icons/icon.svg"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link type="icon" rel="icon" href={metadata.icon} />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </Head>
      <body className={roboto.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}